FROM jenkins/jenkins:lts
USER root

RUN apt-get update && \
    apt-get install -y wget apt-transport-https && \
    wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y dotnet-sdk-8.0 && \
    export PATH=$PATH:$HOME/dotnet && \
    apt-get clean
	
RUN apt install libc6
RUN apt-get update

USER jenkins



